# Generated by Django 3.1 on 2020-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='content',
        ),
        migrations.AddField(
            model_name='entry',
            name='poem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='poem_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
