# Generated by Django 3.1 on 2020-08-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200829_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pic_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='entry',
            name='pic_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='entry',
            name='pic_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
